# Generated by Django 3.2.3 on 2021-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='a', max_length=100)),
                ('email', models.CharField(default='a@gmail.com', max_length=200, unique=True)),
                ('phone_number', models.IntegerField(default=100)),
                ('address', models.CharField(default='b', max_length=100)),
            ],
        ),
    ]
