# Generated by Django 3.2.3 on 2021-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='last_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
